#!/bin/sh

usb_names=( $(lsusb | cut -d' ' -f7-) )
usb_ports=( $(lsusb | cut -d' ' -f6) )

arr=( $(virsh dumpxml win10 |
    xmlstarlet sel -t -m "/domain/devices/hostdev [@type='usb']" -v "source/vendor/@id" -o ":" -v "source/product/@id" -nl |
    sed -e 's/0x\([0-9a-f]*\)/\1/g') )

i=1
for usb in ${arr[@]}; do
    lsusb | grep -q $usb || {
        echo "USB device $usb not connected right now, removing..."
        vendor=$(echo $usb | cut -d':' -f1)
        product=$(echo $usb | cut -d':' -f2)
        EDITOR="virsh dumpxml win10 | xmlstarlet ed -O -d \"/domain/devices/hostdev[source/vendor/@id='0x$vendor'][source/product/@id='0x$product']\" > " virsh edit win10
    }
done
