#!/bin/sh

usb_names=( $(lsusb | cut -d' ' -f7-) )
usb_ports=( $(lsusb | cut -d' ' -f6) )

arr=( $(virsh dumpxml win10 |
    xmlstarlet sel -t -m "/domain/devices/hostdev [@type='usb']" -v "source/vendor/@id" -o ":" -v "source/product/@id" -nl |
    sed -e 's/0x\([0-9a-f]*\)/\1/g') )

i=1
for usb in ${arr[@]}; do
    res=$(lsusb|grep $usb|cut -d' ' -f7-)
    echo "$i) $res ($usb)"
    ((i++))
done

read chosenidx
((chosenidx--))

chosen_ports=${arr[$chosenidx]}
chosen_vendor=$(echo $chosen_ports|cut -d':' -f1)
chosen_id=$(echo $chosen_ports|cut -d':' -f2)

virsh detach-device win10 /dev/stdin <<EOF
<hostdev mode='subsystem' type='usb' managed='yes'>
    <source>
        <vendor id='0x$chosen_vendor'/>
        <product id='0x$chosen_id'/>
      </source>
</hostdev>
EOF